### ISSUE TITLE
Should not transform enums

### ISSUE THREAD

**Issue by Sytten** [prisma/codemods#13]
**Describe the bug**
Since enum are runtime objects, they don't belong in the Prisma namespace.

<img width="486" alt="Screen Shot 2020-11-25 at 5 22 15 PM" src="https://user-images.githubusercontent.com/2366731/100287530-cb4b7880-2f42-11eb-9dd4-c25e5d82e171.png">

**Comment by williamluke4** [comment]
@Sytten Could you please follow the bug template as it helps a lot when creating tests and fixing these issues.

**Comment by williamluke4** [comment]
@Sytten this seems related to #15, could you please confirm?

**Comment by Sytten** [comment]
I can try again, but seems to me a regex to detect that it is an enum would be better?
