### ISSUE TITLE
error after running codemods - has no exported member 

### ISSUE THREAD

**Issue by alan345** [prisma/codemods#14]
After running `npx @prisma/codemods update-2.12 ./`

Code was/is
```
import { User } from '@prisma/client'
//replaced by
import { Prisma } from '@prisma/client'


const auth = {
  me: async (parent: any, args: any, ctx: Ctx, info: any): Promise<User> => {}
}
// replaced by
const auth = {
  me: async (parent: any, args: any, ctx: Ctx, info: any): Promise<Prisma.User> => {}
}

```
error dropped: 
```
Namespace '"/Users/alan/Documents/app/nacho/server/node_modules/.prisma/client/index".Prisma' has no exported member 'User'.ts(2694)
```

![image](https://user-images.githubusercontent.com/15246526/100669737-b3913d00-3312-11eb-8f46-f0dba12272d1.png)

**Comment by P4sca1** [comment]
Same! This makes codemods migration totally useless in my case it just broke the code.

**Comment by williamluke4** [comment]
This is most likely because it can't find your schema (See https://github.com/prisma/codemods/issues/15) Could you try to specify your `--schemaPath`

**Comment by P4sca1** [comment]
Seems to be working now. Thanks @williamluke4!
