### ISSUE TITLE
Feature: Prisma 1 -> 2 Codemod

### ISSUE THREAD

**Issue by LawJolla** [prisma/codemods#17]
Thanks for your hard work and great project!

As Migrate becomes stable, many Prisma 1 users will look to update to Prisma 2 but will uncover a mountain of technical debt.  A codemod to update Prisma 1 -> 2 would do wonders to help that debt and improve Prisma/developer relations.  I'm hopeful this can get done because, without it, I don't know how I'll ever have the time to move from Prisma 1.  😢

**Comment by williamluke4** [comment]
I wish but this would require too much work and I don't have the time. Sorry :cry:
