### ISSUE TITLE
findUnique codemod does not work with variables names other than `prisma`

### ISSUE THREAD

**Issue by NMinhNguyen** [prisma/codemods#20]
**Describe the bug**

The codemod expects the Prisma client to be called `prisma` (https://github.com/prisma/codemods/blob/708ff0917153fe5b72158ede8fa17d4852ecc965/transforms/findUnique.ts#L11) and thus it doesn't apply transforms if your `PrismaClient` instance is called anything else, e.g. `client`. Ideally the codemod should trace the import and allow any variable name (identifier).

**Before the codemod**
```
import { PrismaClient } from '@prisma/client'

const client = new PrismaClient();

client.x.findOne({ where: { id: 'test' } });
```

**After the codemod**
```
import { PrismaClient } from '@prisma/client'

const client = new PrismaClient();

client.x.findOne({ where: { id: 'test' } });
```

**Expected output**
```
import { PrismaClient } from '@prisma/client'

const client = new PrismaClient();

client.x.findUnique({ where: { id: 'test' } });
```

**Additional context**

**Comment by williamluke4** [comment]
Hey folks, this should now be supported in `0.7.0`.
 
I have also added the ability to pass in custom instance names (i.e `--instanceNames=myClient`) 
This is helpful when importing already instantiated clients. 
```
import myClient from './myClient'
```
Please reopen if you are still having issues after upgrading
