### ISSUE TITLE
Nexus Schema functions not inspected.

### ISSUE THREAD

**Issue by danhollick** [prisma/codemods#7]
It seems like the codemod doesn't inspect @nexus/schema functions like `mutationField()`. For example the following code is not converted from `findOne` to `findUnique`:
```
export const login = mutationField('login', {
  type: 'User',
  args: {
    email: stringArg({ required: true }),
    password: stringArg({ required: true }),
  },
  async resolve(parent, { email, password }, context) {
    const user = await context.prisma.user.findOne({
      where: { email },
    })
    return user
})
```

Code outside of those functions is converted.

All of these files contain `mutationField()` and most of them required converting.
![Screenshot 2020-11-25 at 09 19 42](https://user-images.githubusercontent.com/13898607/100200763-5dca2880-2eff-11eb-9f22-ba8edbde7b6b.png)

**Comment by williamluke4** [comment]
@danhollick Yes, this is not supported currently. Will see what I can do

**Comment by williamluke4** [comment]
@danhollick Could you check if 0.6.1 fixes this for you :)

**Comment by williamluke4** [comment]
Feel free to reopen if it is not fixed

**Comment by danhollick** [comment]
@williamluke4 there is currently a bug using `@nexus/schema` with prisma client 2.12.0 so I'll need to wait until that's patched before I can test again.

**Comment by janpio** [comment]
What bug are you referring to? Does an issue for this exist @danhollick?

**Comment by danhollick** [comment]
@janpio I think it was fixed already. Might have just been a dependency bump:
https://github.com/graphql-nexus/nexus-plugin-prisma/issues/959
