### ISSUE TITLE
Converts x.prisma.x.findOne to x.prisma.x.findUnique

### ISSUE THREAD

**Issue by AhmedElywa** [prisma/codemods#8]
Most of our uses in GraphQL resolvers so we have something like this 
`ctx.prisma.x.findOne` or `context.prisma.x.findOne` will be great to Converts `x.prisma.x.findOne` to `x.prisma.x.findUnique`

**Comment by williamluke4** [comment]
This should already work in 0.6.1. Could you please confirm your version

**Comment by AhmedElywa** [comment]
My version is `0.5.1`.
I will try the new version for the two issues and back to you

**Comment by williamluke4** [comment]
@AhmedElywa Could you confirm that this is also fixed?

**Comment by AhmedElywa** [comment]
I was trying. 
Yes, Great job it's also fixed.
