### ISSUE TITLE
issue when we already use Prisma name in our files 

### ISSUE THREAD

**Issue by AhmedElywa** [prisma/codemods#9]
If we already using the name Prisma in our file will be great to use `Prisma as AnotherName`

![image](https://user-images.githubusercontent.com/4535142/100226587-9e8a6780-2f28-11eb-8b74-5dc891329850.png)

**Comment by AhmedElywa** [comment]
If I already update this file manually and run `codemods` to fix the other files 

```js
// this one
import { PrismaClient, Prisma as PrismaTypes } from "@prisma/client";
// will be 
import { PrismaClient, Prisma } from "@prisma/client";

// and 

class Prisma extends PrismaClient {
// this type will be Prisma.PrismaTypes.PrismaClientOptions
  constructor(options?: PrismaTypes.PrismaClientOptions) {
    super(options);
  }

  async onDelete(args: onDeleteArgs) {
    const prismaDelete = new PrismaDelete(this);
    await prismaDelete.onDelete(args);
  }
}
```

**Comment by williamluke4** [comment]
@AhmedElywa What version are you using? If you are not already could you try with 0.6.1

**Comment by AhmedElywa** [comment]
Confirm this issue fixed in 0.6.1

**Comment by williamluke4** [comment]
Awesome

**Comment by AhmedElywa** [comment]
> If I already update this file manually and run `codemods` to fix the other files
> 
> ```js
> // this one
> import { PrismaClient, Prisma as PrismaTypes } from "@prisma/client";
> // will be 
> import { PrismaClient, Prisma } from "@prisma/client";
> 
> // and 
> 
> class Prisma extends PrismaClient {
> // this type will be Prisma.PrismaTypes.PrismaClientOptions
>   constructor(options?: PrismaTypes.PrismaClientOptions) {
>     super(options);
>   }
> 
>   async onDelete(args: onDeleteArgs) {
>     const prismaDelete = new PrismaDelete(this);
>     await prismaDelete.onDelete(args);
>   }
> }
> ```

this issue was fixed, but my mean issue was not fixed.

Can we look if Prisma name already in the file we use another name?

**Comment by williamluke4** [comment]
Could you create a new issue for that, using the new bug template :)
